### ISSUE TITLE
Unable to find style file ant-design-pro-layout-blazor.css

### ISSUE THREAD

**Issue by jxcproject** [ant-design-blazor/ant-design-pro-blazor#170]
Project Nuget references AntDesign.ProLayout 0.17.1
index.html references styles
<link href="_content/AntDesign.ProLayout/css/ant-design-pro-layout-blazor.css" rel="stylesheet" />

After running, the browser reports that the style file cannot be found
GET https://localhost:5001/_content/AntDesign.ProLayout/css/ant-design-pro-layout-blazor.css net::ERR_ABORTED 404 (Not Found)

**Comment by ElderJames** [comment]
Thanks for contacting us @jxcproject , this issue have been fixed in v0.17.1.1, please try. 
https://github.com/ant-design-blazor/blazor-pro-components/releases

**Comment by jxcproject** [comment]
Thanks for the reply, @ElderJames  the problem is still the same, I created an example project via AntDesign.Templates, host:wasm, styles:css project are as follows:
[BUG170.zip](https://github.com/ant-design-blazor/ant-design-pro-blazor/files/13793922/BUG170.zip)

**Comment by ElderJames** [comment]
@jxcproject Sorry, please try 0.17.1.2

**Comment by jxcproject** [comment]
The problem has been fixed
